### ISSUE TITLE
Cancelling a transcode

### ISSUE THREAD

**Issue by cowai** [buggedcom/phpvideotoolkit-v2#101]
Inside a PHPVideoToolkit\ProgressHandlerOutput loop can I somehow cancel the transcoding job?
 I have some long running transcodes that sometimes needs to be stopped immediately. I cannot find a stop method anywhere. Any help?

**Comment by buggedcom** [comment]
It's not offered by phpvideotoolkit however you could find the ffmpeg
process and kill it.

**Comment by cowai** [comment]
@buggedcom Alright, thanks for the tip :)
