### ISSUE TITLE
X265 as a Output Format ???

### ISSUE THREAD

**Issue by parth-khant** [buggedcom/phpvideotoolkit-v2#112]
Your Project is amazing, but can you please ADD X265(HEVC) as a output format that we can download from remote server ?????

**Comment by buggedcom** [comment]
If you create a pull request I will merge.

**Comment by parth-khant** [comment]
I don't know so much php that's why i'm asking you to create the php code for the operation i asked you...

**Comment by ivany4** [comment]
FYI, I've created a PR for this
#119
