### ISSUE TITLE
Unable to set audio codec to libfdk_aac using setAudioCodec()

### ISSUE THREAD

**Issue by tsmgeek** [buggedcom/phpvideotoolkit-v2#38]
When trying to change audio codec to libfdk_aac you get an exception.
I suspect it is due to the way the toolkit finds out what codecs the system can accept.

Output from ffmpeg, as you can see on the aac line it shows the different enc/decoders in the description.

    [console]# ../tools/ffmpeg -codecs|grep aac
    ffmpeg version 2.4.3 Copyright (c) 2000-2014 the FFmpeg developers
      built on Nov 24 2014 15:04:17 with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-4)
      configuration: --prefix=/root/ffmpeg_build --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --bindir=/root/bin --enable-gpl --enable-nonfree --enable-libfdk_aac --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libfreetype
      libavutil      54.  7.100 / 54.  7.100
      libavcodec     56.  1.100 / 56.  1.100
      libavformat    56.  4.101 / 56.  4.101
      libavdevice    56.  0.100 / 56.  0.100
      libavfilter     5.  1.100 /  5.  1.100
      libswscale      3.  0.100 /  3.  0.100
      libswresample   1.  1.100 /  1.  1.100
      libpostproc    53.  0.100 / 53.  0.100
     DEA.L. aac                  AAC (Advanced Audio Coding) (decoders: aac libfdk_aac ) (encoders: aac libfdk_aac )
     D.A.L. aac_latm             AAC LATM (Advanced Audio Coding LATM syntax)

**Comment by buggedcom** [comment]
?
