### ISSUE TITLE
extractFrames() problem

### ISSUE THREAD

**Issue by hanserdev** [buggedcom/phpvideotoolkit-v2#44]
Hi, the extractFrames  function for extract multiple thumbnails of a video don't work for me..
The single extractFrame()  work well, but the multiple extraction produces only 1 image.

And if i use 
```php
$frames = $process->getOutput();
        $frame_paths = array();
        if(empty($frames) === false)
        {
            foreach ($frames as $frame)
            {
                array_push($frame_paths, $frame->getMediaPath());
            }
        }
    }
```
for get array, like the docs suggest i have this error:

```
Fatal error: Uncaught exception 'PHPVideoToolkit\FfmpegProcessOutputException' with message 'Encoding failed and an error was returned from ffmpeg. Error code  was returned the message (if any) was: av_interleaved_write_frame(): Invalid argument' in FfmpegProcessProgressable.php on line 208
```

i use this for processing:

```php
$filePath = 'input\videoplayback.mp4';
$outputPath = 'output\test_%timecode.jpg';

$output_format = new ImageFormat_Jpeg('output', $this->config());
$video  = new Video($filePath, $this->config());
$process = $video->extractFrames(new Timecode(40), new Timecode(50), 1)
  ->save($outputPath, $output_format);
```

..Other tasks like transcoding and seems work well without errors.

But.. i run this on windows.. and i read that does not work well on windows system..i had also these warning  when inizialize:

```
Notice: Use of undefined constant PATH - assumed 'PATH' in Mime.php on line 83
Notice: Use of undefined constant DS - assumed 'DS' in Mime.php on line 83
Notice: Use of undefined constant DS - assumed 'DS' in Mime.php on line 83
Warning: Invalid argument supplied for foreach() in Mime.php on line 203
```
I use 2.1.5 version with raccomanded ffmpeg version.

**Comment by buggedcom** [comment]
Your error ```Fatal error: Uncaught exception 'PHPVideoToolkit\FfmpegProcessOutputException' with message 'Encoding failed and an error was returned from ffmpeg. Error code  was returned the message (if any) was: av_interleaved_write_frame(): Invalid argument' in FfmpegProcessProgressable.php on line 208``` is an ffmpeg error and is nothing that PHPVideoToolkit can control. It suggest an error with your version of ffmpeg.

I will look into fixing the undefined constants issue now.
