### ISSUE TITLE
Timeout in ProgressHandlerNative

### ISSUE THREAD

**Issue by sonnb** [buggedcom/phpvideotoolkit-v2#53]
Hello,

I am getting this issue in one of my user:

Maximum execution time of 120 seconds exceeded -ProgressHandlerNative:99. Which is:

```php
for($i=1, $l=count($data_parts)-1; $i<$l; $i+=2)
{
    $data[$data_parts[$i]] = $data_parts[$i+1];
}
```
What could be the problem here? I do not see a reason for this loop take up to few seconds.

**Comment by buggedcom** [comment]
Without looking at your log file I couldn't be sure, but it is most likely that the whole script timed out and it is was just this part of the script that it timed out on. Make sense?

**Comment by sonnb** [comment]
How can I just call the convert and it returns immediately without waiting? Because even timeout but the progress is still being processed. I just want to call the convert with progressHandler without waiting for this process.

**Comment by buggedcom** [comment]
instead of calling `save`, call `saveNonBlocking` instead. See example 2 of this section of the readme https://github.com/buggedcom/phpvideotoolkit-v2#encoding-with-progress-handlers

**Comment by sonnb** [comment]
Thanks. Do not believe I did not think about it even I red above method.

**Comment by sonnb** [comment]
Thanks to your help. I would like to close this issue for now as I consider it is resolved.
