### ISSUE TITLE
Phpvideotoolkit - "maxlen '=>' 3072 ' in buggedcom \ phpvideotoolkit \ src \ PHPVideoToolkit \ Mime.php line 202"

### ISSUE THREAD

**Issue by xcollado** [buggedcom/phpvideotoolkit-v2#54]
Hello,
I'm trying to integrate PHPVideoToolKit in Symfony2, to generate prviews some videos.

Running directly from PHP I have no problem and works properly, but when in full in Symfony2, I stuck when he tells me that you can not convert a file larger than 3072.

"maxlen '=>' 3072 ')) in C: \ xampp \ htdocs \ www \ VideoLab \ vendor \ buggedcom \ phpvideotoolkit \ src \ PHPVideoToolkit \ Mime.php line 202"

I added the Symfony library by:
"require": {
"ffmpeg-php / php-ffmpeg" "dev-master"
         "pulse00 / ffmpeg-bundle": "dev-master"
         "buggedcom / phpvideotoolkit" "dev-master"

and I installed all the libraries correctly in the Vendors.

Not if you've encountered the problem and have a possible solution.

![image](https://cloud.githubusercontent.com/assets/12529436/7727106/1b2c455e-ff07-11e4-9c0e-611c83ed5a9a.png)

![image](https://cloud.githubusercontent.com/assets/12529436/7727124/2e60f4d0-ff07-11e4-94e5-93adba2b9114.png)

Than You very much
Xavier Collado

**Comment by buggedcom** [comment]
I believe this comes down to an error in the way XAMP is handling the mime reading and the mime_content_type drop in replacement function that is used in Mime.php. The quickest solution would be to ensure that your php install has access to `finfo_buffer` by having the finfo module installed http://php.net/manual/en/fileinfo.installation.php either through the default build if 5.3+ or if below then through pecl. http://pecl.php.net/package/Fileinfo.

Or you can ensure that your system has a `mime_magic.magicfile` (or similar) file that the Mime.php (lines #83-85) can use. Alternatively if XAMPP uses a different file let me know it and I will add it in.

**Comment by xcollado** [comment]
Hello,

I have enabled php_fileinfo.dll in config.ini XAMPP and everything worked perfectly.

Thank you very much for everything
Xavier Collado
