### ISSUE TITLE
Error installing from composer

### ISSUE THREAD

**Issue by rahilwazir** [buggedcom/phpvideotoolkit-v2#65]
I'm getting the error when trying to `composer update`

**composer.json**

    "buggedcom/phpvideotoolki": "*"

> The requested package buggedcom/phpvideotoolki could not be found in any version, there may be a typo in the package name.

**Comment by rahilwazir** [comment]
Ok It solved by running

    $ composer require buggedcom/phpvideotoolkit

I'm closing this but I still want to know why that former didn't work?

**Comment by buggedcom** [comment]
you were missing a "t" at the end of the package name.

**Comment by rahilwazir** [comment]
@buggedcom lol :expressionless:
