### ISSUE TITLE
Please merge bug fixes and enhancement

### ISSUE THREAD

**Issue by SamarRizvi** [buggedcom/phpvideotoolkit-v2#85]
Hi @buggedcom 
I have multiple pull requests and commit waiting to be merged. If they seem fit to you, please merge. I am using your library through composer. Hence, after running composer update every time, I have to overwrite you library with my set of changes.

**Comment by buggedcom** [comment]
Hi Samar, Sorry I haven't the time at the moment, So I've blindly accepted your pull requests and tagged 2.2.2 for you.
