### ISSUE TITLE
How to use with ffmpeg emulator

### ISSUE THREAD

**Issue by Jelle-S** [buggedcom/phpvideotoolkit-v2#98]
I can't seem to find the documentation on how to use this with the ffmpeg emulator classes. 

When I go to /documentation/examples.your-ffmpeg-setup.php I get an error trace stating "FFmpeg appears to be unavailable on your system."

**Comment by buggedcom** [comment]
it's not a ffmpeg emulator. it's a ffmpeg-php emulator - which is a php module. You still need to have php installed on your box for it to work.
