### ISSUE TITLE
% symbol stripped from ffmpeg command

### ISSUE THREAD

**Issue by SamarRizvi** [buggedcom/phpvideotoolkit-v2#99]
% symbol gets stripped out from resulting ffmpeg command (tested in Windows) causing error when a person tries PHPVideoToolkit for multiple output like frame every x seconds, etc.

**Comment by SamarRizvi** [comment]
@buggedcom If time permits, can you please merge this pull request. I have to manually change code whenever I do composer update and stuff due to this.

**Comment by buggedcom** [comment]
Merged, but not had time to check thoroughly so will have to trust you that it works.

**Comment by buggedcom** [comment]
released under 2.2.4
